### ISSUE TITLE
120 fps support

### ISSUE THREAD

**Issue by scrivoluce** [modbrin/libchanger#1]
This application rocks. Why dont you implement also 120 fps lib??

**Comment by modbrin** [comment]
@scrivoluce Hello, actually i implemented the 120 fps lib a long time ago, but the the 800x600 crop is really buggy. Anyway, i can release it today.

**Comment by scrivoluce** [comment]
It would be great!! Thanks for your effort!!

Il giorno mar 16 dic 2014 01:25 PM modbrin notifications@github.com ha
scritto:

**Comment by modbrin** [comment]
@scrivoluce  New version is out now. You can test it

**Comment by scrivoluce** [comment]
Thanks modbrin, works like charms!! Tested on nexus 5 5.0.1.

Il giorno mer 17 dic 2014 07:53 PM modbrin notifications@github.com ha
scritto:
